// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	orderer "github.com/hyperledger/fabric/protos/orderer"
	mock "github.com/stretchr/testify/mock"
)

// AtomicBroadcastServer is an autogenerated mock type for the AtomicBroadcastServer type
type AtomicBroadcastServer struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: _a0
func (_m *AtomicBroadcastServer) Broadcast(_a0 orderer.AtomicBroadcast_BroadcastServer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(orderer.AtomicBroadcast_BroadcastServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deliver provides a mock function with given fields: _a0
func (_m *AtomicBroadcastServer) Deliver(_a0 orderer.AtomicBroadcast_DeliverServer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(orderer.AtomicBroadcast_DeliverServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
