// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HeartbeatSuspects is an autogenerated mock type for the HeartbeatSuspects type
type HeartbeatSuspects struct {
	mock.Mock
}

// GetSuspects provides a mock function with given fields:
func (_m *HeartbeatSuspects) GetSuspects() []uint64 {
	ret := _m.Called()

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}
