// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/smartbft/committee.proto

package smartbft // import "github.com/hyperledger/fabric/protos/orderer/smartbft"

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CommitteeFeedback holds committee related info
type CommitteeFeedback struct {
	Suspects             []int32  `protobuf:"varint,1,rep,packed,name=suspects,proto3" json:"suspects,omitempty"`
	Reconshares          [][]byte `protobuf:"bytes,2,rep,name=reconshares,proto3" json:"reconshares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitteeFeedback) Reset()         { *m = CommitteeFeedback{} }
func (m *CommitteeFeedback) String() string { return proto.CompactTextString(m) }
func (*CommitteeFeedback) ProtoMessage()    {}
func (*CommitteeFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_committee_6a0f51a5654d2071, []int{0}
}
func (m *CommitteeFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitteeFeedback.Unmarshal(m, b)
}
func (m *CommitteeFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitteeFeedback.Marshal(b, m, deterministic)
}
func (dst *CommitteeFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitteeFeedback.Merge(dst, src)
}
func (m *CommitteeFeedback) XXX_Size() int {
	return xxx_messageInfo_CommitteeFeedback.Size(m)
}
func (m *CommitteeFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitteeFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_CommitteeFeedback proto.InternalMessageInfo

func (m *CommitteeFeedback) GetSuspects() []int32 {
	if m != nil {
		return m.Suspects
	}
	return nil
}

func (m *CommitteeFeedback) GetReconshares() [][]byte {
	if m != nil {
		return m.Reconshares
	}
	return nil
}

func init() {
	proto.RegisterType((*CommitteeFeedback)(nil), "smartbft.CommitteeFeedback")
}

func init() {
	proto.RegisterFile("orderer/smartbft/committee.proto", fileDescriptor_committee_6a0f51a5654d2071)
}

var fileDescriptor_committee_6a0f51a5654d2071 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x8e, 0xc2, 0x30,
	0x0c, 0x40, 0x75, 0x57, 0xdd, 0xa9, 0xca, 0xdd, 0x42, 0xa7, 0x8a, 0x29, 0x62, 0xea, 0x94, 0x0c,
	0x88, 0x1f, 0x00, 0x89, 0x9d, 0x8e, 0x6c, 0x49, 0xea, 0xa6, 0x15, 0x04, 0x57, 0xb6, 0x3b, 0xf0,
	0xf7, 0x48, 0x94, 0xa2, 0x8a, 0xd1, 0x7e, 0x7a, 0xf2, 0xb3, 0xd2, 0x48, 0x0d, 0x10, 0x90, 0xe5,
	0xe4, 0x48, 0x7c, 0x2b, 0x36, 0x60, 0x4a, 0xbd, 0x08, 0x80, 0x19, 0x08, 0x05, 0x8b, 0x7c, 0x26,
	0x9b, 0x93, 0x5a, 0x1d, 0x66, 0x78, 0x04, 0x68, 0xbc, 0x0b, 0x97, 0x62, 0xad, 0x72, 0x1e, 0x79,
	0x80, 0x20, 0x5c, 0x7e, 0xe9, 0xac, 0xfa, 0xa9, 0xdf, 0x73, 0xa1, 0xd5, 0x1f, 0x41, 0xc0, 0x1b,
	0x77, 0x8e, 0x80, 0xcb, 0x6f, 0x9d, 0x55, 0xff, 0xf5, 0x72, 0xb5, 0x8f, 0xca, 0x20, 0x45, 0xd3,
	0xdd, 0x07, 0xa0, 0x2b, 0x34, 0x11, 0xc8, 0xb4, 0xce, 0x53, 0x1f, 0xa6, 0xe3, 0x6c, 0x5e, 0x79,
	0x66, 0x8e, 0x38, 0xef, 0x62, 0x2f, 0xdd, 0xe8, 0x4d, 0xc0, 0x64, 0x17, 0x9a, 0x9d, 0x34, 0x3b,
	0x69, 0xf6, 0xf3, 0x2b, 0xff, 0xfb, 0x04, 0xdb, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x9a,
	0x2d, 0xbf, 0xf0, 0x00, 0x00, 0x00,
}
