// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/smartbft/configuration.proto

package smartbft // import "github.com/hyperledger/fabric/protos/orderer/smartbft"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Options_Rotation int32

const (
	Options_UNDEFINED Options_Rotation = 0
	Options_OFF       Options_Rotation = 1
	Options_ON        Options_Rotation = 2
)

var Options_Rotation_name = map[int32]string{
	0: "UNDEFINED",
	1: "OFF",
	2: "ON",
}
var Options_Rotation_value = map[string]int32{
	"UNDEFINED": 0,
	"OFF":       1,
	"ON":        2,
}

func (x Options_Rotation) String() string {
	return proto.EnumName(Options_Rotation_name, int32(x))
}
func (Options_Rotation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_configuration_fd8e544a425114a1, []int{2, 0}
}

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "smartbft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_fd8e544a425114a1, []int{0}
}
func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (dst *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(dst, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	ConsenterId          uint64   `protobuf:"varint,1,opt,name=consenter_id,json=consenterId,proto3" json:"consenter_id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MspId                string   `protobuf:"bytes,4,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	Identity             []byte   `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,6,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,7,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	SelectionPk          []byte   `protobuf:"bytes,8,opt,name=selection_pk,json=selectionPk,proto3" json:"selection_pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_fd8e544a425114a1, []int{1}
}
func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (dst *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(dst, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetConsenterId() uint64 {
	if m != nil {
		return m.ConsenterId
	}
	return 0
}

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetMspId() string {
	if m != nil {
		return m.MspId
	}
	return ""
}

func (m *Consenter) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

func (m *Consenter) GetSelectionPk() []byte {
	if m != nil {
		return m.SelectionPk
	}
	return nil
}

// Options to be specified for all the smartbft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	RequestBatchMaxCount      uint64           `protobuf:"varint,2,opt,name=request_batch_max_count,json=requestBatchMaxCount,proto3" json:"request_batch_max_count,omitempty"`
	RequestBatchMaxBytes      uint64           `protobuf:"varint,3,opt,name=request_batch_max_bytes,json=requestBatchMaxBytes,proto3" json:"request_batch_max_bytes,omitempty"`
	RequestBatchMaxInterval   string           `protobuf:"bytes,4,opt,name=request_batch_max_interval,json=requestBatchMaxInterval,proto3" json:"request_batch_max_interval,omitempty"`
	IncomingMessageBufferSize uint64           `protobuf:"varint,5,opt,name=incoming_message_buffer_size,json=incomingMessageBufferSize,proto3" json:"incoming_message_buffer_size,omitempty"`
	RequestPoolSize           uint64           `protobuf:"varint,6,opt,name=request_pool_size,json=requestPoolSize,proto3" json:"request_pool_size,omitempty"`
	RequestForwardTimeout     string           `protobuf:"bytes,7,opt,name=request_forward_timeout,json=requestForwardTimeout,proto3" json:"request_forward_timeout,omitempty"`
	RequestComplainTimeout    string           `protobuf:"bytes,8,opt,name=request_complain_timeout,json=requestComplainTimeout,proto3" json:"request_complain_timeout,omitempty"`
	RequestAutoRemoveTimeout  string           `protobuf:"bytes,9,opt,name=request_auto_remove_timeout,json=requestAutoRemoveTimeout,proto3" json:"request_auto_remove_timeout,omitempty"`
	ViewChangeResendInterval  string           `protobuf:"bytes,10,opt,name=view_change_resend_interval,json=viewChangeResendInterval,proto3" json:"view_change_resend_interval,omitempty"`
	ViewChangeTimeout         string           `protobuf:"bytes,11,opt,name=view_change_timeout,json=viewChangeTimeout,proto3" json:"view_change_timeout,omitempty"`
	LeaderHeartbeatTimeout    string           `protobuf:"bytes,12,opt,name=leader_heartbeat_timeout,json=leaderHeartbeatTimeout,proto3" json:"leader_heartbeat_timeout,omitempty"`
	LeaderHeartbeatCount      uint64           `protobuf:"varint,13,opt,name=leader_heartbeat_count,json=leaderHeartbeatCount,proto3" json:"leader_heartbeat_count,omitempty"`
	CollectTimeout            string           `protobuf:"bytes,14,opt,name=collect_timeout,json=collectTimeout,proto3" json:"collect_timeout,omitempty"`
	SyncOnStart               bool             `protobuf:"varint,15,opt,name=sync_on_start,json=syncOnStart,proto3" json:"sync_on_start,omitempty"`
	SpeedUpViewChange         bool             `protobuf:"varint,16,opt,name=speed_up_view_change,json=speedUpViewChange,proto3" json:"speed_up_view_change,omitempty"`
	LeaderRotation            Options_Rotation `protobuf:"varint,17,opt,name=leader_rotation,json=leaderRotation,proto3,enum=smartbft.Options_Rotation" json:"leader_rotation,omitempty"`
	DecisionsPerLeader        uint64           `protobuf:"varint,18,opt,name=decisions_per_leader,json=decisionsPerLeader,proto3" json:"decisions_per_leader,omitempty"`
	CommitteeConfig           *CommitteeConfig `protobuf:"bytes,19,opt,name=committee_config,json=committeeConfig,proto3" json:"committee_config,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}         `json:"-"`
	XXX_unrecognized          []byte           `json:"-"`
	XXX_sizecache             int32            `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_fd8e544a425114a1, []int{2}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (dst *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(dst, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetRequestBatchMaxCount() uint64 {
	if m != nil {
		return m.RequestBatchMaxCount
	}
	return 0
}

func (m *Options) GetRequestBatchMaxBytes() uint64 {
	if m != nil {
		return m.RequestBatchMaxBytes
	}
	return 0
}

func (m *Options) GetRequestBatchMaxInterval() string {
	if m != nil {
		return m.RequestBatchMaxInterval
	}
	return ""
}

func (m *Options) GetIncomingMessageBufferSize() uint64 {
	if m != nil {
		return m.IncomingMessageBufferSize
	}
	return 0
}

func (m *Options) GetRequestPoolSize() uint64 {
	if m != nil {
		return m.RequestPoolSize
	}
	return 0
}

func (m *Options) GetRequestForwardTimeout() string {
	if m != nil {
		return m.RequestForwardTimeout
	}
	return ""
}

func (m *Options) GetRequestComplainTimeout() string {
	if m != nil {
		return m.RequestComplainTimeout
	}
	return ""
}

func (m *Options) GetRequestAutoRemoveTimeout() string {
	if m != nil {
		return m.RequestAutoRemoveTimeout
	}
	return ""
}

func (m *Options) GetViewChangeResendInterval() string {
	if m != nil {
		return m.ViewChangeResendInterval
	}
	return ""
}

func (m *Options) GetViewChangeTimeout() string {
	if m != nil {
		return m.ViewChangeTimeout
	}
	return ""
}

func (m *Options) GetLeaderHeartbeatTimeout() string {
	if m != nil {
		return m.LeaderHeartbeatTimeout
	}
	return ""
}

func (m *Options) GetLeaderHeartbeatCount() uint64 {
	if m != nil {
		return m.LeaderHeartbeatCount
	}
	return 0
}

func (m *Options) GetCollectTimeout() string {
	if m != nil {
		return m.CollectTimeout
	}
	return ""
}

func (m *Options) GetSyncOnStart() bool {
	if m != nil {
		return m.SyncOnStart
	}
	return false
}

func (m *Options) GetSpeedUpViewChange() bool {
	if m != nil {
		return m.SpeedUpViewChange
	}
	return false
}

func (m *Options) GetLeaderRotation() Options_Rotation {
	if m != nil {
		return m.LeaderRotation
	}
	return Options_UNDEFINED
}

func (m *Options) GetDecisionsPerLeader() uint64 {
	if m != nil {
		return m.DecisionsPerLeader
	}
	return 0
}

func (m *Options) GetCommitteeConfig() *CommitteeConfig {
	if m != nil {
		return m.CommitteeConfig
	}
	return nil
}

type CommitteeConfig struct {
	CommitteeMinimumLifespan   uint32    `protobuf:"varint,1,opt,name=committee_minimum_lifespan,json=committeeMinimumLifespan,proto3" json:"committee_minimum_lifespan,omitempty"`
	FailedTotalNodesPercentage uint64    `protobuf:"varint,2,opt,name=failed_total_nodes_percentage,json=failedTotalNodesPercentage,proto3" json:"failed_total_nodes_percentage,omitempty"`
	InverseFailureChance       uint64    `protobuf:"varint,3,opt,name=inverse_failure_chance,json=inverseFailureChance,proto3" json:"inverse_failure_chance,omitempty"`
	MandatoryNodes             []int32   `protobuf:"varint,4,rep,packed,name=mandatory_nodes,json=mandatoryNodes,proto3" json:"mandatory_nodes,omitempty"`
	Weights                    []*Weight `protobuf:"bytes,5,rep,name=weights,proto3" json:"weights,omitempty"`
	Disabled                   bool      `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}  `json:"-"`
	XXX_unrecognized           []byte    `json:"-"`
	XXX_sizecache              int32     `json:"-"`
}

func (m *CommitteeConfig) Reset()         { *m = CommitteeConfig{} }
func (m *CommitteeConfig) String() string { return proto.CompactTextString(m) }
func (*CommitteeConfig) ProtoMessage()    {}
func (*CommitteeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_fd8e544a425114a1, []int{3}
}
func (m *CommitteeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitteeConfig.Unmarshal(m, b)
}
func (m *CommitteeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitteeConfig.Marshal(b, m, deterministic)
}
func (dst *CommitteeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitteeConfig.Merge(dst, src)
}
func (m *CommitteeConfig) XXX_Size() int {
	return xxx_messageInfo_CommitteeConfig.Size(m)
}
func (m *CommitteeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitteeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CommitteeConfig proto.InternalMessageInfo

func (m *CommitteeConfig) GetCommitteeMinimumLifespan() uint32 {
	if m != nil {
		return m.CommitteeMinimumLifespan
	}
	return 0
}

func (m *CommitteeConfig) GetFailedTotalNodesPercentage() uint64 {
	if m != nil {
		return m.FailedTotalNodesPercentage
	}
	return 0
}

func (m *CommitteeConfig) GetInverseFailureChance() uint64 {
	if m != nil {
		return m.InverseFailureChance
	}
	return 0
}

func (m *CommitteeConfig) GetMandatoryNodes() []int32 {
	if m != nil {
		return m.MandatoryNodes
	}
	return nil
}

func (m *CommitteeConfig) GetWeights() []*Weight {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *CommitteeConfig) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Weight struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weight) Reset()         { *m = Weight{} }
func (m *Weight) String() string { return proto.CompactTextString(m) }
func (*Weight) ProtoMessage()    {}
func (*Weight) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_fd8e544a425114a1, []int{4}
}
func (m *Weight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weight.Unmarshal(m, b)
}
func (m *Weight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weight.Marshal(b, m, deterministic)
}
func (dst *Weight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weight.Merge(dst, src)
}
func (m *Weight) XXX_Size() int {
	return xxx_messageInfo_Weight.Size(m)
}
func (m *Weight) XXX_DiscardUnknown() {
	xxx_messageInfo_Weight.DiscardUnknown(m)
}

var xxx_messageInfo_Weight proto.InternalMessageInfo

func (m *Weight) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Weight) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "smartbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "smartbft.Consenter")
	proto.RegisterType((*Options)(nil), "smartbft.Options")
	proto.RegisterType((*CommitteeConfig)(nil), "smartbft.CommitteeConfig")
	proto.RegisterType((*Weight)(nil), "smartbft.Weight")
	proto.RegisterEnum("smartbft.Options_Rotation", Options_Rotation_name, Options_Rotation_value)
}

func init() {
	proto.RegisterFile("orderer/smartbft/configuration.proto", fileDescriptor_configuration_fd8e544a425114a1)
}

var fileDescriptor_configuration_fd8e544a425114a1 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x95, 0x6f, 0x6f, 0xdb, 0xb6,
	0x13, 0xc7, 0x7f, 0x72, 0x1c, 0xc7, 0xa1, 0xe3, 0x3f, 0x61, 0xd2, 0x54, 0xcd, 0x6f, 0x03, 0x5c,
	0x63, 0xd8, 0x8c, 0x0c, 0xb0, 0x8b, 0x74, 0x1d, 0x06, 0x6c, 0xc3, 0xd0, 0x38, 0x0d, 0x96, 0xa1,
	0xf9, 0x03, 0x36, 0xdd, 0x80, 0x3d, 0x21, 0x68, 0xe9, 0x2c, 0x13, 0x95, 0x48, 0x8d, 0xa4, 0x92,
	0xa6, 0x2f, 0x68, 0xef, 0x61, 0xef, 0x6d, 0x0f, 0x06, 0x92, 0x92, 0xec, 0x25, 0x7b, 0x66, 0xdd,
	0xf7, 0xf3, 0xbd, 0xe3, 0x5d, 0x98, 0x23, 0xfa, 0x42, 0xaa, 0x18, 0x14, 0xa8, 0xa9, 0xce, 0x98,
	0x32, 0xf3, 0x85, 0x99, 0x46, 0x52, 0x2c, 0x78, 0x52, 0x28, 0x66, 0xb8, 0x14, 0x93, 0x5c, 0x49,
	0x23, 0x71, 0xbb, 0x52, 0x47, 0x0a, 0xf5, 0x66, 0x0e, 0xb8, 0x00, 0xc3, 0x62, 0x66, 0x18, 0x7e,
	0x89, 0x50, 0x24, 0x85, 0x06, 0x61, 0x40, 0xe9, 0x30, 0x18, 0x6e, 0x8c, 0x3b, 0xc7, 0x7b, 0x93,
	0xca, 0x30, 0x99, 0x55, 0x1a, 0x59, 0xc3, 0xf0, 0xd7, 0x68, 0x4b, 0xe6, 0xb6, 0x80, 0x0e, 0x1b,
	0xc3, 0x60, 0xdc, 0x39, 0xde, 0x5d, 0x39, 0xae, 0xbc, 0x40, 0x2a, 0x62, 0xf4, 0x77, 0x80, 0xb6,
	0xeb, 0x34, 0xf8, 0x39, 0xda, 0xa9, 0x13, 0x51, 0x1e, 0x87, 0xc1, 0x30, 0x18, 0x37, 0x49, 0xa7,
	0x8e, 0x9d, 0xc7, 0x18, 0xa3, 0xe6, 0x52, 0x6a, 0xe3, 0x52, 0x6f, 0x13, 0xf7, 0xdb, 0xc6, 0x72,
	0xa9, 0x4c, 0xb8, 0x31, 0x0c, 0xc6, 0x5d, 0xe2, 0x7e, 0xe3, 0x27, 0xa8, 0x95, 0xe9, 0xdc, 0x26,
	0x69, 0x3a, 0x72, 0x33, 0xd3, 0xf9, 0x79, 0x8c, 0x0f, 0x51, 0x9b, 0xc7, 0x20, 0x0c, 0x37, 0xf7,
	0xe1, 0xe6, 0x30, 0x18, 0xef, 0x90, 0xfa, 0x1b, 0x7f, 0x89, 0xfa, 0x51, 0xca, 0x41, 0x18, 0x6a,
	0x52, 0x4d, 0x23, 0x50, 0x26, 0x6c, 0x39, 0xa4, 0xeb, 0xc3, 0x37, 0xa9, 0x9e, 0x81, 0x32, 0x96,
	0xd3, 0xa0, 0x6e, 0x41, 0xad, 0xb8, 0x2d, 0xcf, 0xf9, 0x70, 0xc5, 0x3d, 0x47, 0x3b, 0x1a, 0x52,
	0x88, 0x6c, 0xa7, 0x34, 0xff, 0x10, 0xb6, 0x1d, 0xd4, 0xa9, 0x63, 0xd7, 0x1f, 0x46, 0x7f, 0xb6,
	0xd1, 0x56, 0x39, 0x13, 0xfc, 0x0a, 0x3d, 0x55, 0xf0, 0x47, 0x01, 0xda, 0xd0, 0x39, 0x33, 0xd1,
	0x92, 0x66, 0xec, 0x23, 0x8d, 0x64, 0x21, 0x7c, 0xb3, 0x4d, 0xb2, 0x5f, 0xca, 0x27, 0x56, 0xbd,
	0x60, 0x1f, 0x67, 0x56, 0xfb, 0x6f, 0xdb, 0xfc, 0xde, 0x80, 0x76, 0xf3, 0x78, 0x6c, 0x3b, 0xb1,
	0x1a, 0xfe, 0x1e, 0x1d, 0x3e, 0xb6, 0x71, 0x3b, 0xe4, 0x5b, 0x96, 0x96, 0x33, 0x7b, 0xfa, 0xc0,
	0x79, 0x5e, 0xca, 0xf8, 0x27, 0xf4, 0x19, 0x17, 0x91, 0xcc, 0xb8, 0x48, 0x68, 0x06, 0x5a, 0xb3,
	0x04, 0xe8, 0xbc, 0x58, 0x2c, 0x40, 0x51, 0xcd, 0x3f, 0x81, 0x9b, 0x6c, 0x93, 0x3c, 0xab, 0x98,
	0x0b, 0x8f, 0x9c, 0x38, 0xe2, 0x1d, 0xff, 0x04, 0xf8, 0x08, 0xed, 0x56, 0xd5, 0x73, 0x29, 0x53,
	0xef, 0x6a, 0x39, 0x57, 0xbf, 0x14, 0xae, 0xa5, 0x4c, 0x1d, 0xfb, 0xed, 0xaa, 0xc1, 0x85, 0x54,
	0x77, 0x4c, 0xc5, 0xd4, 0xf0, 0x0c, 0x64, 0xe1, 0xc7, 0xbe, 0x4d, 0x9e, 0x94, 0xf2, 0x99, 0x57,
	0x6f, 0xbc, 0x88, 0xbf, 0x43, 0x61, 0xe5, 0x8b, 0x64, 0x96, 0xa7, 0x8c, 0x8b, 0xda, 0xd8, 0x76,
	0xc6, 0x83, 0x52, 0x9f, 0x95, 0x72, 0xe5, 0xfc, 0x11, 0xfd, 0xbf, 0x72, 0xb2, 0xc2, 0x48, 0xaa,
	0x20, 0x93, 0xb7, 0x50, 0x9b, 0xb7, 0x9d, 0xb9, 0x4a, 0xfe, 0xba, 0x30, 0x92, 0x38, 0x60, 0xcd,
	0x7e, 0xcb, 0xe1, 0x8e, 0x46, 0x4b, 0x26, 0x12, 0xa0, 0x0a, 0x34, 0x88, 0x78, 0x35, 0x5b, 0xe4,
	0xed, 0x16, 0x99, 0x39, 0x82, 0x38, 0xa0, 0x1e, 0xee, 0x04, 0xed, 0xad, 0xdb, 0xab, 0xaa, 0x1d,
	0x67, 0xdb, 0x5d, 0xd9, 0xd6, 0xfa, 0x4c, 0x81, 0xc5, 0xa0, 0xe8, 0x12, 0xec, 0xbf, 0x19, 0x30,
	0x53, 0x9b, 0x76, 0x7c, 0x9f, 0x5e, 0xff, 0xb9, 0x92, 0x2b, 0xe7, 0x37, 0xe8, 0xe0, 0x91, 0xd3,
	0x5f, 0xb8, 0xae, 0xbf, 0x39, 0x0f, 0x7c, 0xfe, 0xc2, 0x7d, 0x85, 0xfa, 0x91, 0x4c, 0xed, 0x1d,
	0xae, 0xcb, 0xf4, 0x5c, 0x99, 0x5e, 0x19, 0xae, 0xd2, 0x8f, 0x50, 0x57, 0xdf, 0x8b, 0x88, 0x4a,
	0x41, 0xb5, 0x61, 0xca, 0x84, 0xfd, 0x61, 0x30, 0x6e, 0x93, 0x8e, 0x0d, 0x5e, 0x89, 0x77, 0x36,
	0x84, 0xa7, 0x68, 0x5f, 0xe7, 0x00, 0x31, 0x2d, 0x72, 0xba, 0xd6, 0x75, 0x38, 0x70, 0xe8, 0xae,
	0xd3, 0xde, 0xe7, 0xbf, 0xd6, 0x4d, 0xe3, 0x19, 0xea, 0x97, 0x67, 0x56, 0xd2, 0xb8, 0x3d, 0x16,
	0xee, 0x0e, 0x83, 0x71, 0xef, 0xf8, 0xf0, 0xd1, 0x96, 0x99, 0x90, 0x92, 0x20, 0x3d, 0x6f, 0xa9,
	0xbe, 0xf1, 0x0b, 0xb4, 0x1f, 0x43, 0xc4, 0xb5, 0xa5, 0x68, 0x0e, 0x8a, 0x7a, 0x3d, 0xc4, 0xae,
	0x6d, 0x5c, 0x6b, 0xd7, 0xa0, 0xde, 0x3a, 0x05, 0x9f, 0xa2, 0x41, 0x24, 0xb3, 0x8c, 0x1b, 0x03,
	0x40, 0xfd, 0x1a, 0x0d, 0xf7, 0xdc, 0x76, 0x7b, 0xb6, 0xbe, 0x0f, 0x4b, 0xc2, 0xaf, 0x51, 0xd2,
	0x8f, 0xfe, 0x1d, 0x18, 0x1d, 0xa1, 0x76, 0x7d, 0x86, 0x2e, 0xda, 0x7e, 0x7f, 0x79, 0xfa, 0xe6,
	0xec, 0xfc, 0xf2, 0xcd, 0xe9, 0xe0, 0x7f, 0x78, 0x0b, 0x6d, 0x5c, 0x9d, 0x9d, 0x0d, 0x02, 0xdc,
	0x42, 0x8d, 0xab, 0xcb, 0x41, 0xe3, 0x97, 0x66, 0x3b, 0x18, 0x34, 0x48, 0xcb, 0xd7, 0x1a, 0xfd,
	0xd5, 0x40, 0xfd, 0x07, 0xe9, 0xf1, 0x0f, 0xe8, 0x70, 0x75, 0xa6, 0x8c, 0x0b, 0x9e, 0x15, 0x19,
	0x4d, 0xf9, 0x02, 0x74, 0xce, 0x84, 0xdb, 0x9d, 0x5d, 0x12, 0xd6, 0xc4, 0x85, 0x07, 0xde, 0x96,
	0x3a, 0x7e, 0x8d, 0x3e, 0x5f, 0x30, 0x9e, 0x42, 0x4c, 0x8d, 0x34, 0x2c, 0xa5, 0x42, 0xc6, 0xe0,
	0x86, 0x11, 0x81, 0x30, 0x2c, 0x81, 0x72, 0xe9, 0x1c, 0x7a, 0xe8, 0xc6, 0x32, 0x97, 0x16, 0xb9,
	0xae, 0x09, 0x7b, 0x7f, 0xb8, 0xb8, 0x05, 0xa5, 0x81, 0x5a, 0xaa, 0x50, 0xe0, 0xfe, 0x7c, 0x11,
	0x54, 0x9b, 0xa7, 0x54, 0xcf, 0xbc, 0x38, 0x73, 0x9a, 0xbd, 0x3f, 0x19, 0x13, 0x31, 0x33, 0x52,
	0xdd, 0xfb, 0xaa, 0x61, 0x73, 0xb8, 0x31, 0xde, 0x24, 0xbd, 0x3a, 0xec, 0x0a, 0xe1, 0x23, 0xb4,
	0x75, 0x07, 0x3c, 0x59, 0x1a, 0x1d, 0x6e, 0xba, 0xa7, 0x67, 0xb0, 0x1a, 0xf5, 0x6f, 0x4e, 0x20,
	0x15, 0x60, 0xf7, 0x7a, 0xcc, 0x35, 0x9b, 0xa7, 0x10, 0xbb, 0x3d, 0xd2, 0x26, 0xf5, 0xf7, 0xe8,
	0x05, 0x6a, 0x79, 0x1c, 0xf7, 0x50, 0xa3, 0x7c, 0x55, 0x36, 0x49, 0x83, 0xc7, 0xf8, 0x00, 0xb5,
	0x7c, 0x02, 0xd7, 0x6c, 0x97, 0x94, 0x5f, 0x27, 0x09, 0x9a, 0x48, 0x95, 0x4c, 0x96, 0xf7, 0x39,
	0xa8, 0x14, 0xe2, 0x04, 0xd4, 0x64, 0xc1, 0xe6, 0x8a, 0x47, 0xfe, 0xcd, 0xd4, 0x93, 0xf2, 0x65,
	0xad, 0xcf, 0xf3, 0xfb, 0xab, 0x84, 0x9b, 0x65, 0x31, 0x9f, 0x44, 0x32, 0x9b, 0xae, 0xd9, 0xa6,
	0xde, 0x36, 0xf5, 0xb6, 0xe9, 0xc3, 0x07, 0x79, 0xde, 0x72, 0xc2, 0xcb, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xf3, 0x58, 0xd1, 0x63, 0xab, 0x07, 0x00, 0x00,
}
