name: Publish docker image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish image to dockerhub
      run: bash scripts/publish_images.sh

